---
driver:
  name: docker
  use_sudo: false
  image: kevinhcross/chef
  require_chef_omnibus: false
  use_cache: true

# This should also work according to https://github.com/test-kitchen/test-kitchen/issues/315
#driver:
#  name: docker
#  provision_command: curl -L https://www.getchef.com/chef/install.sh | bash

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: policyfile_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
  - name: ubuntu
    run_list:
    - recipe[apt]
#  - name: centos-7.1

suites:
  - name: default
    attributes:
