---

driver:
  name: vagrant

# Docker set up that will avoid downloading chef every test run
# Now using vagrant/virtualbox as systemd does has issues on docker
#driver:
#  name: docker
#  use_sudo: false
#  provision_command: curl -L https://www.getchef.com/chef/install.sh | bash
#  require_chef_omnibus: false

# This was me trying to get docker working with services being run by systemd
# I don't think this is going to work as the container is not being started with init
#driver:
#  name: docker
#  use_sudo: false
#  # This is to get avoid installing chef omnibus every time we run
#  image: kevinhcross/centos-systemd
#  provision_command: curl -L https://www.getchef.com/chef/install.sh | bash
#  require_chef_omnibus: false
#  use_cache: true

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: policyfile_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
#  - name: ubuntu
#    run_list:
#    - recipe[apt]
  - name: centos-7.1

suites:
  - name: default
    attributes:

