name 'my-elk-stack-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures my-elk-stack-cookbook'
long_description 'Installs/Configures my-elk-stack-cookbook'
version '1.0.2'
